### ISSUE TITLE
IntelliSense crash, when editing VSCT

### ISSUE THREAD

**Issue by phofman** [madskristensen/ExtensibilityTools#1]
I tried to use this project with my [BlackBerry NDK plugin](/phofman/vs-plugin), which has some simple UI inside Visual Studio and found following issue.

![intellisense_exception1](https://cloud.githubusercontent.com/assets/475630/7168993/b7f39e34-e3c1-11e4-9c6c-a8342ec7aef1.jpg)

or 

![intellisense_exception2](https://cloud.githubusercontent.com/assets/475630/7169016/e58a75b6-e3c1-11e4-8ac0-5dd315dded03.jpg)

It seems to be caused, when you actually type inside the VSCT file and the XML is still **invalid** due to unclosed tags. At the end of the day CTRL+Space might lead to some strange exceptions inside your code here:

![tracked_exception1](https://cloud.githubusercontent.com/assets/475630/7168997/b99931e0-e3c1-11e4-89be-794806a2c8d8.jpg)

**Comment by madskristensen** [comment]
Great. Thanks for reporting this
