### ISSUE TITLE
Intellisense for Visual Studio Resources

### ISSUE THREAD

**Issue by mojtabakaviani** [madskristensen/ExtensibilityTools#13]
Please add intellisense for Visual Studio Resources such as VsBrushs, VsColors and Glyphs that can create better extension same visual studio interface and themes

```
Background="{DynamicResource VsBrush.Window}"
```
by default not work

**Comment by madskristensen** [comment]
@mlorbetske isn't this exactly what you planned on adding?

**Comment by mojtabakaviani** [comment]
when use resources show warning,  The resource "VsBrush.Window" could not be resolved.

**Comment by mlorbetske** [comment]
@madskristensen kind of, I was going with having a picker for the theme resources used by VS for a selected point which would produce an appropriate binding string and xmlns declaration for the  resource
