### ISSUE TITLE
IntelliSense crash on Enter key

### ISSUE THREAD

**Issue by phofman** [madskristensen/ExtensibilityTools#2]
Similar to #1. When you start typing in VSCT file and hit enter in the middle of the XML attribute, you might end up with following failure:

![intellisense_exception3](https://cloud.githubusercontent.com/assets/475630/7169159/449f882e-e3c3-11e4-85e1-ed37b66ed626.jpg)

This seems to be caused here:

![tracked_exception3](https://cloud.githubusercontent.com/assets/475630/7169196/a044f984-e3c3-11e4-9d19-c5ae97ef6745.jpg)

**Comment by madskristensen** [comment]
Thanks for the bug report. I'll release an update soon with the latest fixes
