### ISSUE TITLE
Vsct synchronization generates a .cs files with Tabs, regardless of the Visual Studio settings

### ISSUE THREAD

**Issue by hmemcpy** [madskristensen/ExtensibilityTools#28]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: [example 1.6.138]

### Description
The "Auto-sync VSCT" command generates a .cs file that is using tabs for indentation, instead of the C# style configured in Visual Studio.
![image](https://cloud.githubusercontent.com/assets/601206/13989254/36ed0cc0-f118-11e5-94d0-ddb7343e89c8.png)

### Current behavior
Generates tabs.

### Expected behavior
Should generate the indent character and size, depending on the user's Visual Studio preferences.

**Comment by hmemcpy** [comment]
Yeesh, I meant Resx sync!

**Comment by madskristensen** [comment]
> Yeesh, I meant Resx sync!

??

**Comment by hmemcpy** [comment]
The menu, I meant "Auto-sync Resx and Icon files", not VSCT... too late to change the commit message, I guess.

**Comment by madskristensen** [comment]
oh, yeah :)

Thanks for the PR

**Comment by hmemcpy** [comment]
Sure :) Thanks for the extension!
