### ISSUE TITLE
Code contribution

### ISSUE THREAD

**Issue by phofman** [madskristensen/ExtensibilityTools#3]
Hi Mads,

Do you accept code contributions?

I wish to add a feature, that drives me crazy the most, when working with VSCT files. I think about the code generator that takes the CmdIDs and GUIDs from VSCT and places them respectively into C#/VB code to be used, when dealing with [CommandID](https://msdn.microsoft.com/en-us/library/system.componentmodel.design.commandid(v=vs.110).aspx).

**Comment by madskristensen** [comment]
Sure I do :)

Yeah, that is super annoying to do that manually. How do you think it should work?

**Comment by phofman** [comment]
I would do it the easiest way I know ;)

VSPackage could export custom code-generator via [ProvideCodeGenerator](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.texttemplating.vshost.providecodegeneratorattribute.aspx). This generator could inherit from [BaseCodeGeneratorWithSite](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.texttemplating.vshost.basecodegeneratorwithsite.aspx) to have access to all VS services (DTE in particular).

For selected VSCT file dev should set the 'Custom Tool' with the name of this code-generator.
Then it will automatically scan for GuidSymbol/IDSymbol elements and their values from the source VSCT and use the CodeDom (matching the current language of the project) to emit the result code as partial classes with GUIDs/string/int fields.

The solution is more-less already written in my [old TytanNET plugin](http://tytannet.codeplex.com/wikipage?title=VsctGenerator). I will probably need to cleanup it up a bit, but I don't expect much problems.

**Comment by madskristensen** [comment]
That's a great idea!

**Comment by phofman** [comment]
Great, I will try to add it shortly.

**Comment by madskristensen** [comment]
will it add a build target to the .csproj file or is it a tooling thing only? It would be best if the code generation worked on CI servers etc. and didn't require this extension to be installed to work

**Comment by madskristensen** [comment]
A NuGet package can modify the .csproj file and include the task when its installed and then this extension would add the correct codegen properties to the .vsct file entry in the .csproj file.

**Comment by madskristensen** [comment]
Actually, if the code file is generated and checked in to source control, then there is no need for a CI ready mechanism through MSBuild I guess

**Comment by phofman** [comment]
No, no, probably the 'custom tool' part misguided you somehow ;) It's just a common property of any file in the project:

![customtool](https://cloud.githubusercontent.com/assets/475630/7198357/cf6a9a56-e4eb-11e4-8e71-455afdba71de.jpg)

The same way the .resx file is processed for example (that generates the code-part). There is nothing running behind during the build itself. And you never ever have a separate executable anywhere. All code is still in your 'VSPackage' library. It works like that:

1) developer puts a name VsctGenerator (or whatever we call that generator) inside the 'Custom Tool' field (which is stored inside .csproj, among the item's child tags)
2) Visual Studio looks for a generator with respective name among all extensions (via registry and/or .pkgdef files) 
3) if is not found - it doesn't show any errors etc., won't break the build, nothing, simply ignored
4) if is found - creates an instance of VsctGenerator class and passes the whole content of the source file to that generator via [IVsSingleFileGenerator](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivssinglefilegenerator.aspx) interface. Generator returns processed content, which is then stored by Visual Studio in a file next to the source one and is visually added as source-file's child item.
5) jump to step 2 each time source-file is edited and saved, what will automatically recreate content of the generated file
6) if developer removed the VsctGenerator from 'Custom Tool' field, the file gets deleted automatically 

So it will work on CI, as you should keep the generated file also in your project/repository to compile. It only removes from dev's shoulders the need of manually updating the command-ids and guids, whenever the selected VSCT file is updated.

Do we need that 'Generate GUIDs' button? I don't think so. Beside the single custom-tool setup, first time you create VSCT file, you don't need it anymore.

**Comment by madskristensen** [comment]
Thanks for clarifying. This sounds really cool. Send the PR :)

**Comment by phofman** [comment]
OK. Pushed the code. Feel free to review and comment.

**Comment by phofman** [comment]
Closing, since merged and released.
