### ISSUE TITLE
'Auto-sync Resx and Icon Files' does not creates the .ico for 'Meta/source.extension.vsixmanifest'

### ISSUE THREAD

**Issue by misoftware** [madskristensen/ExtensibilityTools#31]
### Installed product versions
- Visual Studio: 2015 Community
- This extension: 1.7.154

### Description
I keep my .vsixmanifest file in a subfolder of the project, say, ```MyProject/Meta/source.extension.vsixmanifest```

**Problem is:** ```Auto-sync Resx and Icon Files``` does not find the Resources\icon.png to create the respective .ico

### Steps to recreate
1. make sure Resources/icon.png exists
2. create a 'Meta' subfolder in the project
3. move ```source.extension.vsixmanifest``` inside it
4. right-click ```source.extension.vsixmanifest``` and click ```Auto-sync Resx and Icon Files```
 
### Current behavior
It creates ```Meta/source.extension.cs``` and ```Meta/source.extension.resx```, but does creates ```Meta/source.extension.ico```

### Expected behavior
```Meta/source.extension.ico``` should be created from the existing ```Resources/icon.png```

**Comment by KindDragon** [comment]
It doesn't create ico for me only if png image added to extension project as link. It's works well if I'll add it in the usual way

**Comment by techcap** [comment]
If source.extension.vsixmanifest is not exist in root, it doesn't generate ico file for me too.
