### ISSUE TITLE
Crash in Extensibility Tools

### ISSUE THREAD

**Issue by RenniePet** [madskristensen/ExtensibilityTools#36]
### Installed product versions
- Visual Studio: 2015 Professional
- This extension: 1.7.154

### Description
Just getting started with trying to create a VS extension. Not sure what's happening.

### Steps to recreate
Going through steps specified here https://msdn.microsoft.com/en-us/library/dd885492.aspx
for "Creating a Classifier Extension".

### Current behavior
When I press F5 to build and run I get the crash shown in the attached image. A mouse-over for DTE.Solution.FullName indicates that it is an empty string.

![extensibilitytoolscrash](https://cloud.githubusercontent.com/assets/4259011/15217553/4c66c6f2-185c-11e6-89f3-fc55b39a119a.png)

### Expected behavior
Yesterday, before installing the ExtensibilityTools extension, it worked OK.

As well as installing ExtensibilityTools, I've also cloned it and I'd loaded it into Visual Studio and tried to gain insight into how extensions work by hitting F5 to run it as a test. That was probably a mistake because that crashed too. Can't remember if it was the same crash, probably.

**Comment by RenniePet** [comment]
Presumably trying to run Extensibility Tools as a test extension by hitting F5 was a mistake, and it's apparently a mistake which huge consequences. I've now completely uninstalled ExtensibilityTools from my Visual Studio and rebooted my PC and I'm still getting this crash when trying to follow the instructions in https://msdn.microsoft.com/en-us/library/dd885492.aspx !

**Comment by RenniePet** [comment]
This is getting worse and worse. I've now removed my local clone of Extensibility Tools from the local GitHub folder, and I'm still getting a crash. 

![extensibilitytoolscrash2](https://cloud.githubusercontent.com/assets/4259011/15219290/80c2dc86-1863-11e6-98a0-7bdd92ec8db0.png)

I don't understand what's going on here. I'm not trying to do anything with Extensibility Tools at this point, I'm just trying to take the first baby steps in learning how to create a VS extension.

**Comment by RenniePet** [comment]
OK, after some Googling around I found this http://www.codeproject.com/Tips/832362/Resetting-the-Visual-Studio-Experimental-Instance and that fixed the problem.

On one hand I really appreciate that you created this extension. I expect that I'll be able to use some of what you've done in an extension I'm planning on making.

On the other hand, could you please make a change so that doing what I (stupidly?) did and cloning your project and hitting F5 to try it out doesn't have such drastic consequences. That has cost me quite a bit of time and has given me a bad initial impression of Visual Studio extension development.

**Comment by madskristensen** [comment]
Hitting F5 in this project didn't cause the issue you were describing. There must have been some sort of MEF cache corruption or similar going on and launching the Experimental Instance must have triggered something bad to happen

**Comment by RenniePet** [comment]
Well, for what it's worth it's reproducible for me. I've just re-cloned your project locally again, loaded it into Visual Studio, hit F5 and gotten the same crash. And from then on the experimental instance is kaput - if I try to test the minimal extension at https://msdn.microsoft.com/en-us/library/dd885492.aspx the same crash occurs again.

But I have discovered that if I add these two statements to the start of your PrepareForAppVeyor.BeforeQueryStatus() method then it stops crashing.

            if (DTE.Solution.FullName == "")
                return;

**Comment by madskristensen** [comment]
That is very strange. Thanks for looking in to it. I'll add your fix
