### ISSUE TITLE
Suggestion: add the version of the TextBuffer

### ISSUE THREAD

**Issue by midiway** [madskristensen/ExtensibilityTools#37]
This is a very simpler one: add to the status bar the Version of the ITextSnapshot the caret is currently in, something like:
```C#
ITextSnapshot snap = ...;// get the snapshot from the ITextBuffer that contains the caret
snap.Version.ToString();
```
Today the status-bar already contains the Content type beneath the caret right?
So it would be just an additional information

**Comment by madskristensen** [comment]
Great idea. I'll add it as a tooltip on the content type
