### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by phofman** [madskristensen/ExtensibilityTools#5]
Few hints/ideas, if you don't mind:

1) I also created some time ago a [tool](/phofman/signature) to digitally sign VSIX packages for public releases; maybe this could be also integrated into this plugin?
2) if you have a code-signing certificate, you could sign this plugin too ;)
3) if you edit README.md, I suggest doing it directly via github page, after clicking the file on the list and then [Edit] icon on the toolbar; then you will have an option to preview changes at runtime, before commit
4) thanks for placing me in credits
5) when you are doing releases, it's better to mark them with git tags, instead of placing version numbers in comments, as then github puts a special care and source is zipped plus could be downloaded from [releases list page](/madskristensen/ExtensibilityTools/releases) without the need of repo clone; finally binaries could be assigned for these releases too

**Comment by madskristensen** [comment]
1. Sounds interesting. How would this be implemented for this extension?
2. I don't and don't plan to
3. I use Web Essentials which gives full rendered preview. Doesn't catch all my typos however :)
4. Thank you!!!
5. I do that to remind myself. I sometimes create GitHub releases also. Just did that. Thanks for the heads up. I don't use any features of Git really, other than pushing and pulling
