### ISSUE TITLE
Code-signing Support

### ISSUE THREAD

**Issue by phofman** [madskristensen/ExtensibilityTools#6]
It would be nice to have some option helping in signing VSIX package. Such a package presents **Digital Signature** text about the author, when installing manually and its content is validated by Installer/Extension Manager. Similar to this one about me:

![signing](https://cloud.githubusercontent.com/assets/475630/7219772/08dfc0f2-e6b0-11e4-8572-972cd7b9bb2f.jpg)

From the code perspective, it is fairly easy to implement. Some playing around with [PackageDigitalSignatureManager](https://msdn.microsoft.com/en-us/library/System.IO.Packaging.PackageDigitalSignatureManager_methods(v=vs.110).aspx) and already compiled package. Check [this sample code from MSDN](https://msdn.microsoft.com/en-us/library/system.io.packaging.packagedigitalsignaturemanager.sign(v=vs.110).aspx). Anyway, I already have it implemented and working in my [Signature](/phofman/signature) tool.

The mandatory option is to allow using preinstalled certificate and/or one from .pfx file (with password).

Optionally, beside VSIX package, it could also sign regular Windows binaries for any other kinds of project supported by Visual Studio. However, it's handled a bit differently, i.e. by executing `signtool.exe` tool with proper parameters (not in C# code only).

The harder part, is where to place it inside Visual Studio:
* as additional property page of VSIX project? - doable via custom Project Flavor AFAIK, but the biggest flaw is that devs might have problems opening such a project, when the extension is not installed
* as a custom tool window? - simple toolwindow suggesting output binaries produced by all projects with ability to select certificate
* a 'Sign Binary...' menu option, when right-clicking the project node in Solution Explorer and certificate options are specified via extension option page

Any suggestions welcome.

**Comment by madskristensen** [comment]
Can we have an MSBuild target perform the signing on build? The options are stored as properties in the .csproj file and will be populated by a GUI provided in this extension as you suggest. The task it calls would be in a nuget package. That way it would work on a CI server. The only issue I can see with that approach is how to store the password for CI scenarios. Perhaps @sayedihashimi has an idea?

**Comment by sayedihashimi** [comment]
If you are using appveyor you can encrypt the password on their site and insert the encrypted pwd in the appveyor.yml file and it can only be decrypted from that account. If you are not using appveyor then if your CI server doesn't support a secrets store then you can use env variables or a file that is in source control that only the CI account has access to.

**Comment by phofman** [comment]
I like the idea of having dedicated nuget package to enable signing. But I wouldn't rather store password for CI in project itself. For these kinds of scenarios I would rather suggest using preinstalled nonexportable certificate and let to select it via thumbprint or some regex over issuer name or as Sayed suggested use registry/separate file, which might not be even commited, but just exist on CI. (@sayedihashimi thx for your answer, and just by my own curiosity - could you point me to any doc, how to generate the secure encrypted password? Do you mean [ProtectedData](https://msdn.microsoft.com/en-us/library/system.security.cryptography.protecteddata(v=vs.90).aspx).Protect(), or something custom?)

Other thing that bothers me most is - what path should be placed in .csproj to correctly load .targets file from the package? NuGet packages are stored under $Solution$/packages, while the project could be possibly anywhere. This could potentially fail pretty quickly:
`<Import Project="$(MSBuildProjectDirectory)\..\packages\**\Sign.targets" />`
Would this one work better?
`<Import Project="$(MSBuildStartupDirectory)\packages\**\Sign.targets" />`
 If you build from solution level then probably yes. If single project from command-line - probably not.

Do you have any better recipe?



And just for future reference - `Sign.targets` that will print the (relative and full) path to VSIX to sign, after build:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="SignVsix" AfterTargets="CreateVsixContainer">
        <Message Text="Signing VSIX container: '$(TargetVsixContainer)' - @(_CreatedVsixContainer->'%(FullPath)')" Importance="High" />
    </Target>
</Project>
```

**Comment by sayedihashimi** [comment]
@phofman 

>could you point me to any doc, how to generate the secure encrypted password? Do you mean ProtectedData.Protect(), or something custom?)

I was saying that if you are using http://appveyor.com, they have a way to encrypt values and place them in ```appveyor.yml```. If you want to handle it yourself I'd recommend you reach out a security expert like @blowdart

>Other thing that bothers me most is - what path should be placed in .csproj to correctly load .targets file from the package? 

When the package is installed you can find out where the packages folder is located. For example take a look at how I do this in SlowCheetah - [```install.ps1```](https://github.com/sayedihashimi/slow-cheetah/blob/master/NuGet/tools/Install.ps1). Note: you can simplify that by using [psbuild](https://github.com/ligershark/psbuild) to handle things like ```Test-Property```,```Add-Property```,```Add-Import``` etc. I created the SlowCheetah install script before I created psbuild. If you need help with that let me know. Also the PowerShell in SlowCheetah could be improved, but it works.

**Comment by blowdart** [comment]
Code signing ought to be for released bits and not automatic as part of a build. Adobe learnt that the hard way when build servers were compromised and used to issue signed malware (http://blogs.adobe.com/security/2012/09/inappropriate-use-of-adobe-code-signing-certificate.html).

So I am loathe to recommend anything here except for "Don't do this".

**Comment by phofman** [comment]
Thanks all for inputs.

I did dropped any CI support and NuGet, went back to simple button and code executed on machine with VS installed. Check PR #7 for details and pictures. Now it's @madskristensen turn to decide and review ;)
