### ISSUE TITLE
Microsoft.VisualStudio.Composition.PartDiscoveryException: Failure while scanning type "MadsKristensen.ExtensibilityTools.ExtensibilityToolsPackage".

### ISSUE THREAD

**Issue by SamuelEnglard** [madskristensen/ExtensibilityTools#62]
### Installed product versions
- Visual Studio: Enterprise 2017 15.6.4
- This extension: 1.10.200

### Description
Fails to load package

### Steps to recreate
Start Visual Studio

### Current behavior
[Microsoft.VisualStudio.Default.txt](https://github.com/madskristensen/ExtensibilityTools/files/1856070/Microsoft.VisualStudio.Default.txt)

### Expected behavior
Load

**Comment by madskristensen** [comment]
I'm guessing you don't have VS 2015 installed on the same machine, correct?

**Comment by rtigithub** [comment]
I am experiencing similar problem.  I do not have VS2015 on this machine.

**Comment by SamuelEnglard** [comment]
@madskristensen yup 😄

**Comment by madskristensen** [comment]
Then I know exactly what the issue is. It's potentially tricky and I hope I don't have to split the extension into two - one for 2015 and one for 2017

**Comment by madskristensen** [comment]
Can you try this build on a machine with only VS2017 and see if it works? http://vsixgallery.com/extension/f8330d54-0469-43a7-8fc0-7f19febeb897/

**Comment by laxxifer** [comment]
Hi @madskristensen,
I have the same problem. With the build of the previous post it seems to work correctly.
I have only VS2017 in my machine.

**Comment by SamuelEnglard** [comment]
@madskristensen no issues now!

**Comment by madskristensen** [comment]
Excellent. Thanks for testing the new VSIX. I just uploaded it to the marketplace

**Comment by SamuelEnglard** [comment]
@madskristensen I've got the VSIX Gallery as a extension feed so I got it automatically
